# Generated by Django 4.1.3 on 2022-11-13 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nem13', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accumulationmeterdata',
            name='current_reason_code',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='accumulationmeterdata',
            name='nmi',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='accumulationmeterdata',
            name='previous_reason_code',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='accumulationmeterdata',
            name='record_indicator',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='b2bdetails',
            name='record_indicator',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='end',
            name='record_indicator',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='header',
            name='record_indicator',
            field=models.IntegerField(),
        ),
    ]
