# Generated by Django 4.1.3 on 2022-11-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nem13', '0002_alter_accumulationmeterdata_current_reason_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accumulationmeterdata',
            name='previous_reason_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
