# Generated by Django 4.1.3 on 2022-11-14 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nem13', '0005_alter_accumulationmeterdata_file_path_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accumulationmeterdata',
            unique_together={('file_path', 'nmi')},
        ),
    ]
