# Generated by Django 4.1.3 on 2022-11-14 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nem13', '0006_alter_accumulationmeterdata_unique_together'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='accumulationmeterdata',
            name='nem13_accum_file_pa_dc30b6_idx',
        ),
    ]
