# Generated by Django 4.1.3 on 2022-11-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nem13', '0010_accumulationmeterdata_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accumulationmeterdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='accumulationmeterdata',
            name='nmi',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
