# Generated by Django 4.1.3 on 2022-11-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nem13', '0011_remove_accumulationmeterdata_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accumulationmeterdata',
            name='id',
            field=models.BigAutoField(auto_created=True, default=3, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accumulationmeterdata',
            name='nmi',
            field=models.IntegerField(),
        ),
    ]
