# Generated by Django 4.1.3 on 2022-11-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nem13', '0012_accumulationmeterdata_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2bdetails',
            name='current_ret_service_order',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='b2bdetails',
            name='current_trans_code',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
